# Config relating to the Lazygit UI
gui:
  # If true, do not show a warning when amending a commit.
  skipAmendWarning: true

  # If true, do not show a warning when discarding changes in the staging view.
  skipDiscardChangeWarning: true

  # If true, do not show warning when applying/popping the stash
  skipStashWarning: true

  # If true, do not show a warning when rewording a commit via an external editor
  skipRewordInEditorWarning: true

  # If true, increase the height of the focused side window; creating an accordion effect.
  expandFocusedSidePanel: true

  # If true, hunk selection mode will be enabled by default when entering the staging view.
  useHunkModeInStagingView: false

  # How things are filtered when typing '/'.
  # One of 'substring' (default) | 'fuzzy'
  filterMode: fuzzy

  # Status panel view.
  # One of 'dashboard' (default) | 'allBranchesLog'
  statusPanelView: allBranchesLog

  # If true, when using the panel jump keys (default 1 through 5) and target panel
  # is already active, go to next tab instead
  switchTabsWithPanelJumpKeys: true

  # Config relating to the spinner.
  spinner:
    # The frames of the spinner animation.
    frames:
      - '|'
      - /
      - '-'
      - \

    # The "speed" of the spinner in milliseconds.
    rate: 50

git:
  # Config for showing the log in the commits view
  log:
    # displays the whole git graph by default in the commits view (equivalent to
    # passing the `--all` argument to `git log`)
    showWholeGraph: false

# If true, don't display introductory popups upon opening Lazygit.
disableStartupPopups: false

# User-configured commands that can be invoked from within Lazygit
# See https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md
customCommands:
  - key: '<c-a>'
    context: global
    description: 'Force amend and push changes'
    command: 'bash -c "git add -A ; git commit --amend --no-edit ; git push --force-with-lease"'
    prompts:
      - type: 'confirm'
        title: 'Reset branch to origin'
        body: 'Are you sure you want to force amend and push {{ .SelectedLocalBranch.Name }} to origin?'

  - key: '<c-r>'
    context: global
    description: 'Reset current branch to origin'
    command: 'git reset --hard origin/{{ .SelectedLocalBranch.Name }}'
    prompts:
    - type: 'confirm'
      title: 'Reset branch to origin'
      body: 'Are you sure you want to reset {{ .SelectedLocalBranch.Name }} to origin?'

# What to do when opening Lazygit outside of a git repo.
# - 'prompt': (default) ask whether to initialize a new repo or open in the most
# recent repo
# - 'create': initialize a new repo
# - 'skip': open most recent repo
# - 'quit': exit Lazygit
notARepository: skip

# If true, display a confirmation when subprocess terminates. This allows you to
# view the output of the subprocess before returning to Lazygit.
promptToReturnFromSubprocess: false


